### ISSUE TITLE
UB: ODR violation

### ISSUE THREAD

**Issue by Nekrolm** [Nekrolm/ubbook#29]

**Comment by LDVSOFT** [comment]
Решил проверить есть ли эта тема здесь, потому что примерчик построился сладкий.
```
#include <functional>

struct A {};
struct B{};
struct D : B {};

bool operator<(A a, B b) { std::exit(1); }
void demo_1() { A a; D d; std::less<void> comparator; comparator(a, d); }

bool operator<(A a, D d) { std::exit(2); }
void demo_2() { A a; D d; std::less<void> comparator; comparator(a, d); }

int main() {
    demo_1();
    demo_2();
    return 0;
}
```
GCC/Clang: exit 1, MSVC: exit 2.

**Comment by Nekrolm** [comment]
Если все в одном cpp, то это не ODR-violation, а шляпа с лукапом внутри шаблонов. В msvc, похоже, перестарались с реализацией двухэтапного лукапа и он теперь не просто откладывает лукап до момента инстанциирования шаблона, но еще и в будущее смотреть может. Кто из компиляторов прав тут — честно говоря, не знаю.  Но скорее всего GCC и Clang

А вот если по разным единицам трансляции растащить — то уже да, ODR-violation)
