### ISSUE TITLE
Trap: -pedantic-errors/-Werror=pedantic

### ISSUE THREAD

**Issue by LDVSOFT** [Nekrolm/ubbook#32]
Я не знаю деталей, но посмотрите какой кекс: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=68209#c3 Где-то, где упоминается wall/wextra, возможно стоит порекомендовать -pedantic, заодно может пояснить вариации.

**Comment by Nekrolm** [comment]
Думаю, это какая-то давно устаревшая дичь. Все более-менее современные версии gcc по умолчанию собирают в режиме C++14.
А разбор значений флажков компилятора все-таки выходит немного за рамки темы.
