### ISSUE TITLE
Поддержка сборщика мусора: UB только при strict pointer safety?

### ISSUE THREAD

**Issue by yeputons** [Nekrolm/ubbook#33]
Кажется, что UB от использования хитрых указателей возникает только если у реализации "strict pointer safety" — https://eel.is/c++draft/basic.stc.dynamic.safety#4 

А так обычно у всех "relaxed pointer safety", это implementation-defined, никакого UB.

Можно даже в рантайме проверить: https://en.cppreference.com/w/cpp/memory/gc/get_pointer_safety

И даже под Valgrind, видимо, чисто теоретически подстроиться, если увидел `preferred`

**Comment by Nekrolm** [comment]
Кажется, что тут такая же ерунда, как и с делением на 0 в `float`: UB вообще говоря (и в constexpr вычислениях нельзя), но если `std::numeric_limits<FloatType>::is_iec559 == true`, то все как по спецификации.

Но сноску про проверку надо бы добавить, да
