### ISSUE TITLE
More fun with static initialization order fiasco and standard library

### ISSUE THREAD

**Issue by yeputons** [Nekrolm/ubbook#57]
Even in C++11!

```c++
// a.cpp
#include <iostream>
void print_hello() {
    std::cout << "hello\n";
}
```
```c++
// b.cpp
void print_hello();
struct StaticObject {
    StaticObject() {
        print_hello();
    }
} static_object;
int main() {
}
```

If I compile these two locally with `g++ -std=c++17 a.cpp b.cpp`, the resulting `a.exe` crashes. My compiler version is `g++ (Rev2, Built by MSYS2 project) 10.3.0` on Windows.
I am also able to reproduce this behavior by compiling `g++ -std=c++17 b.cpp a.cpp` with `g++-10 (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0`

I believe it is because `b.cpp` does not include `<iostream>` and `static_object` gets constructed before anything in `a.cpp`, corresponding `std::ios_base::Init` provided by `<iostream>` in particular. Hence, when `print_hello()` is called, `std::cout` is not initialized yet, hence the crash.

**Comment by Nekrolm** [comment]
https://github.com/Nekrolm/ubbook/blob/master/runtime/static_initialization_order_fiasco.md#initialization-order-fiasco-%D0%B8-%D0%BD%D0%B5%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D1%83%D0%B5%D0%BC%D1%8B%D0%B5-%D0%B7%D0%B0%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BA%D0%B8
