### ISSUE TITLE
Pointer arithmetics on a raw memory is UB

### ISSUE THREAD

**Issue by yeputons** [Nekrolm/ubbook#61]
Apparently it's impossible to implement `std::vector`:
https://stackoverflow.com/questions/60481204/dynamic-arrays-in-c-without-undefined-behavior
https://www.youtube.com/watch?v=IAdLwUXRUvg&t=1267s

In particular:

* You cannot do pointer arithmetics on `T*` without creating `T[]`: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0593r5.html#dynamic-construction-of-arrays , so you should either placement-new an array in a chunk of memory (which will construct elements as well) or allocate `char[]`/`byte[]` and do `char`-based arithmetics to address elements (not sure if it's legal), but you still cannot implement `T* vector::data()`
* Actually, you cannot do array placement new even for `char[]` because it may need an unspecified number of extra bytes: https://stackoverflow.com/questions/15254/can-placement-new-for-arrays-be-used-in-a-portable-way

**Comment by Nekrolm** [comment]
Almost all covered in 
https://github.com/Nekrolm/ubbook/tree/master/pointer_prominence

Maybe I'll add notes about vector implementation.

Also it needs to check references in C++20 standard. There may be changes in wordings related to lifetime beginning in raw memory.

**Comment by Nekrolm** [comment]
Added notes about vector
https://github.com/Nekrolm/ubbook/blob/master/pointer_prominence/invalid_pointer.md
