### ISSUE TITLE
std::aligned_storage instead of std::aligned_storage_t

### ISSUE THREAD

**Issue by GrigorenkoPV** [Nekrolm/ubbook#94]
В pointer_prominence/array_placement_new.md в последней ссылке на godbolt есть
```cpp
using storage = std::aligned_storage<sizeof(S) * 4, alignof(S)>;
```
А должно быть
```cpp
using storage = typename std::aligned_storage<sizeof(S) * 4, alignof(S)>::type;
```
или
```cpp
using storage = std::aligned_storage_t<sizeof(S) * 4, alignof(S)>;
```

Классическая ловушка `_t` (про которую в этом репозитории где-то даже упоминается).

Конкретно с `aligned_storage` всё настолько плохо, что в C++23 его даже депрекэйтнули:
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p1413r3.pdf

**Comment by Nekrolm** [comment]
Спасибо. 

Правда, теперь надо проверить, воспроизводится ли падение или нужно искать другой пример
